### ISSUE TITLE
Error Message On IPython Exit

### ISSUE THREAD

**Issue by aeoranday** [DUNE-DAQ/trgtools#49]
```python
Exception ignored in: <function PDFPlotter.__del__ at 0x7fb183882680>
Traceback (most recent call last):
  File "/nfs/home/mrigan/dune-daq/v5.2-241010/install/trgtools/lib64/python/trgtools/plot/PDFPlotter.py", line 91, in __del__
  File "/nfs/home/mrigan/dune-daq/v5.2-241010/.venv/lib/python3.10/site-packages/matplotlib/backends/backend_pdf.py", line 2721, in close
  File "/nfs/home/mrigan/dune-daq/v5.2-241010/.venv/lib/python3.10/site-packages/matplotlib/backends/backend_pdf.py", line 828, in finalize
  File "/nfs/home/mrigan/dune-daq/v5.2-241010/.venv/lib/python3.10/site-packages/matplotlib/backends/backend_pdf.py", line 974, in writeFonts
  File "/nfs/home/mrigan/dune-daq/v5.2-241010/.venv/lib/python3.10/site-packages/matplotlib/backends/backend_pdf.py", line 1451, in embedTTF
  File "/nfs/home/mrigan/dune-daq/v5.2-241010/.venv/lib/python3.10/site-packages/matplotlib/backends/backend_pdf.py", line 1182, in embedTTFType3
ImportError: sys.meta_path is None, Python is likely shutting down
```

I expect this has to do with a messy garbage collection on the PDFPlotter.

**Comment by ArturSztuc** [comment]
Assigning to `v5.x.x`. @aeoranday can you provide mode details? I never got that exception, do you have some MRE?

**Comment by aeoranday** [comment]
In an interactive session,
```python
from trgtools.plot import PDFPlotter
import numpy as np
pdf = PDFPlotter("test_out.pdf")
a = np.random.randint(0, 10, size=1000)
pdf.plot_histogram(a, {"title": "Test", "xlabel": "x", "ylabel": "y"})
exit()
```

**Comment by ArturSztuc** [comment]
Thanks, could reproduce the error & could confirm your recent PR fixes it.

**Comment by aeoranday** [comment]
Closed by #57.
